application: danpresos
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /AppEngine101
  static_dir: AppEngine101

- url: /AppEngine201
  static_dir: AppEngine201

- url: /namekeepr
  static_dir: namekeepr

- url: /HTML5CssResponsive
  static_dir: HTML5CssResponsive

- url: /IntroToAppEngine
  static_dir: IntroToAppEngine

- url: /.*
  script: danpresos.application
